{{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1" }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: postgres-istio-exceptions
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      cluster-name: pg-cluster
  portLevelMtls:
    "5432":
      mode: PERMISSIVE
{{- end }}