{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-headless
  namespace: postgres
spec:
  clusterIP: None
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
  selector:
    cluster-name: pg-cluster
{{- end }}
