# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporter
  namespace: postgres
spec:
  scrapeClass: istio-certs
  namespaceSelector:
    matchNames:
      - postgres
  podMetricsEndpoints:
    - port: exporter
      scheme: https
      enableHttp2: false
  selector:
    matchLabels:
      application: spilo
{{- end }}
