# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- $uniqueNamespaces := dict }}
{{- range $user, $_ := .Values.postgresql.users }}
  {{- $namespace := (splitList "." $user | first) }}
  {{- if not (hasKey $uniqueNamespaces $namespace) }}
    {{- $_ := set $uniqueNamespaces $namespace true }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ $namespace | quote }}
  {{- end }}
{{- end }}
