{{- if .Values.postgresql.enabled }}
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  network:
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      {{- range .Values.postgresql.ingress }}
      - direction: Ingress
        selector:
          cluster-name: pg-cluster
        {{- . | toYaml | nindent 8 }}
      {{- end }}

      - direction: Ingress
        selector:
          app.kubernetes.io/name: postgres-operator
        remoteNamespace: postgres-operator
        remoteSelector:
          app.kubernetes.io/name: postgres-operator

      - direction: Egress
        selector:
          cluster-name: pg-cluster
        remoteGenerated: KubeAPI
{{- end }}
