# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: create
    description: Create the namespace dependency package
    actions:
      - cmd: uds zarf package create src/namespace --confirm --no-progress --architecture="${UDS_ARCH}" --skip-sbom
