name: Scan

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]

jobs:
  validate:
    name: Lint
    permissions:
      contents: read # Allows reading the repo contents
    uses: defenseunicorns/uds-common/.github/workflows/callable-lint.yaml@243-update-uds-common-gh-actions-to-use-maruuds-run-conditionals
    secrets: inherit # Inherits all secrets from the parent workflow.